### ISSUE TITLE
Remover ícone de imagem.

### ISSUE THREAD

**Issue by pabloedu01** [TUNAP-Brasil/Frontent-Tunapconnect#24]
![image](https://user-images.githubusercontent.com/1905753/234029559-951b2397-2d5f-497a-b52e-9dd5e57c8fb1.png)

**Comment by kleberfreire** [comment]
![image](https://user-images.githubusercontent.com/32939737/234316185-06dd6533-7090-464b-b5d1-e7e1ac161845.png)
